#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     PSPNX,          sensorI2CCustomFastSkipStates)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Rrear,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Rfront,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Lrear,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lfront,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    swirve,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "PS2/includes/PSP-Nx-lib.h"


long map(long x, long in_min, long in_max, long out_min, long out_max)
{
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}

void forward(int magnitude, int direction);
void reverse(int magnitude, int direction);
void left(int magnitude, int direction);
void right(int magnitude, int direction);
void nuetral(int magnitude, int direction);
const ubyte Addr = 0x02;

task main()
{
psp currState;
nI2CBytesReady[PSPNX] = 0;
PlaySound(soundUpwardTones);

while(true)
{
PSP_ReadButtonState(PSPNX, Addr, currState);
bool joystick_joy1_btn_1			= !(char)currState.square;//unused true or false
bool joystick_joy1_btn_2 			= !(char)currState.cross;	//unused
bool joystick_joy1_btn_3 			= !(char)currState.circle;//unused
bool joystick_joy1_btn_4 			= !(char)currState.triang;//unused
bool joystick_joy1_Dpad_Up 		= !(char)currState.d;			//unused
bool joystick_joy1_Dpad_Right = !(char)currState.c;			//unused
bool joystick_joy1_Dpad_Down 	= !(char)currState.b;			//unused
bool joystick_joy1_Dpad_Left 	= !(char)currState.a;			//unused
bool joystick_joy1_L_Bumper		= !(char)currState.l1;		//unused
bool joystick_joy1_R_Bumper		= !(char)currState.r1;		//unused
bool joystick_joy1_L_Trigger	= !(char)currState.l2;		//unused
bool joystick_joy1_R_Trigger	= !(char)currState.r2;		//unused
bool joystick_joy1_btn_13			=	!(char)currState.l_j_b;	//unused
bool joystick_joy1_btn_14			= !(char)currState.r_j_b;	//unused
int joystick_joy1_x1 					= (int)currState.l_j_x;		//(-100)-(100)
int joystick_joy1_y1 					= (int)currState.l_j_y;		//(-100)-(100)
int joystick_joy1_x2					= (int)currState.r_j_x;		//(-100)-(100)
int joystick_joy1_y2					= (int)currState.r_j_y;		//unused (-100)-(100)

  int x = joystick_joy1_x1;
  int y =-joystick_joy1_y1;
  int z = joystick_joy1_x2;
    //determine velocity
  int n_magnitude = 	x + y + z;
  // Scale m_magnitude to represent motor scope more accuratly.
 	int magnitude = map(n_magnitude,-300,300,-100,100);
 	// determine angle.
 	int cartisian = x + y;
 	int angle = map(cartisian,-200,200,0,360);
 	// scale angle for servo...
 	int direction = map(angle,0,360,0,254);
}


}

void forward(int magnitude, int direction)
{
magnitude = 40;
direction = 90;

}
void reverse(int magnitude, int direction)
{
magnitude = 40;
direction = 270;
}
void left(int magnitude, int direction)
{
magnitude = 40;
direction = 180;
}
void right(int magnitude, int direction)
{
magnitude = 40;
direction = 360;
}
void nuetral (int magnitude, int direction)
{
magnitude = 0;
direction = 0;
}
void drive (int M_magnitude, int M_direction)
{
	servo[swirve]= M_direction;
	if(M_magnitude>abs(12))
	{
	motor[Rfront]= M_magnitude;
	motor[Rrear] = M_magnitude;
	motor[Lfront]= M_magnitude;
	motor[Lrear] = M_magnitude;
	}
	else
	{
	motor[Rfront]= 0;
	motor[Rrear] = 0;
	motor[Lfront]= 0;
	motor[Lrear] = 0;
	}
}
